#!/usr/bin/env bash
# Standalone venv for the fastest gfx1151 PyTorch π0.5 SnapFlow path.
#
#   ROCM_ARCH=gfx1151 bash scripts/setup.sh -y
#   source env.sh
set -euo pipefail

PKG_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${PI05_FAST_VENV:-${HOME}/.local/venvs/pi05-pytorch-fast}"
PYTHON_BIN="${PI05_PYTHON:-python3.12}"
ROCM_INDEX="${PI05_ROCM_INDEX:-https://rocm.nightlies.amd.com/whl-multi-arch/}"
ROCM_ARCH="${ROCM_ARCH:-gfx1151}"
ROCM_PREFIX="${ROCM_PATH:-/opt/rocm}"
GFX_OVERRIDE="${HSA_OVERRIDE_GFX_VERSION:-11.5.1}"
CONSTRAINTS="${PI05_TORCH_CONSTRAINTS:-${PKG_ROOT}/constraints-rocm.txt}"
ENV_SNIPPET="${PKG_ROOT}/env.sh"
LEROBOT_REF="${LEROBOT_GIT_REF:-6a788fbdb02cabfae60f7408636945df0b1eafa0}"
LIBERO_SRC="${LIBERO_ROOT:-}"
CLEAN=0
STATUS_ONLY=0
SKIP_SMOKE=0
SKIP_LIBERO=0
ASSUME_YES=0
NO_GFX_OVERRIDE=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Create a ROCm PyTorch venv + LeRobot PI05 + optional LIBERO (no ONNX / MIGraphX).

Options:
  --venv DIR           Virtualenv (default: ${HOME}/.local/venvs/pi05-pytorch-fast)
  --python BIN         Python interpreter (default: python3.12)
  --rocm-index URL     AMD wheel index for torch
  --arch GFX           ROCm arch tag (default: gfx1151)
  --constraints FILE   uv constraints for torch
  --rocm PATH          ROCm prefix for PATH / LD_LIBRARY_PATH
  --no-gfx-override    Omit HSA_OVERRIDE_GFX_VERSION
  --skip-libero        Do not install LIBERO / mujoco
  --clean              Remove existing venv before create
  --skip-smoke         Skip GPU matmul smoke
  --status             Print status and exit
  -y, --yes            Non-interactive (for --clean)
  -h, --help
EOF
}

log() { echo "==> $*"; }
warn() { echo "WARN: $*" >&2; }
die() { echo "ERROR: $*" >&2; exit 1; }

write_env_snippet() {
  {
    echo "# Source for pi05-pytorch-fast — generated by scripts/setup.sh"
    echo "export PI05_FAST_ROOT=\"${PKG_ROOT}\""
    echo "export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=\"\${TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL:-1}\""
    echo "export TORCH_BLAS_PREFER_HIPBLASLT=\"\${TORCH_BLAS_PREFER_HIPBLASLT:-1}\""
    echo "export PYTORCH_HIP_ALLOC_CONF=\"\${PYTORCH_HIP_ALLOC_CONF:-max_split_size_mb:512}\""
    echo "export PI05_COMPILE=\"\${PI05_COMPILE:-1}\""
    echo "export PI05_COMPILE_MODE=\"\${PI05_COMPILE_MODE:-max-autotune-no-cudagraphs}\""
    echo "export PI05_PREFIX_LM_FP16=\"\${PI05_PREFIX_LM_FP16:-1}\""
    echo "export PI05_W4A4_PACK=\"\${PI05_W4A4_PACK:-${PKG_ROOT}/models/w4a4_prefix}\""
    echo "export PI05_W4A4_FUSE_QUANT=\"\${PI05_W4A4_FUSE_QUANT:-1}\""
    echo "# shellcheck disable=SC1091"
    echo "source \"${VENV_DIR}/bin/activate\""
    echo "export PYTHONPATH=\"${PKG_ROOT}:\${PYTHONPATH:-}\""
    if [[ -d "${LIBERO_SRC}/libero" ]]; then
      echo "export LIBERO_ROOT=\"\${LIBERO_ROOT:-${LIBERO_SRC}}\""
      echo "export PYTHONPATH=\"${LIBERO_SRC}:\${PYTHONPATH}\""
    fi
    if [[ -d "${ROCM_PREFIX}/bin" ]]; then
      echo "export PATH=\"${ROCM_PREFIX}/bin:\${PATH}\""
    fi
    if [[ -d "${ROCM_PREFIX}/lib" ]]; then
      echo "export LD_LIBRARY_PATH=\"${ROCM_PREFIX}/lib:\${LD_LIBRARY_PATH:-}\""
    fi
    if [[ "${NO_GFX_OVERRIDE}" != "1" && -n "${GFX_OVERRIDE}" ]]; then
      echo "export HSA_OVERRIDE_GFX_VERSION=\"\${HSA_OVERRIDE_GFX_VERSION:-${GFX_OVERRIDE}}\""
    fi
  } > "${ENV_SNIPPET}"
}

gpu_smoke_test() {
  "${VENV_DIR}/bin/python" - <<'PY'
import torch
print("PyTorch", torch.__version__)
if not torch.cuda.is_available():
    raise SystemExit("FAIL: torch.cuda.is_available() is False")
x = torch.randn(512, 512, device="cuda")
y = x @ x
torch.cuda.synchronize()
print("OK: GPU matmul", tuple(y.shape), "device", torch.cuda.get_device_name(0))
PY
}

status() {
  echo "pi05-pytorch-fast"
  echo "  package root: ${PKG_ROOT}"
  echo "  venv:         ${VENV_DIR}"
  echo "  env snippet:  ${ENV_SNIPPET}"
  echo "  rocm index:   ${ROCM_INDEX}"
  echo "  rocm arch:    ${ROCM_ARCH}"
  if [[ -x "${VENV_DIR}/bin/python" ]]; then
    echo "  python:       $("${VENV_DIR}/bin/python" --version 2>&1)"
    "${VENV_DIR}/bin/python" -c "import torch; print('  torch:', torch.__version__, 'cuda:', torch.cuda.is_available())" 2>/dev/null \
      || echo "  torch:        import failed"
  else
    echo "  venv:         [missing — run scripts/setup.sh]"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --venv) VENV_DIR="$2"; shift 2 ;;
    --python) PYTHON_BIN="$2"; shift 2 ;;
    --rocm-index) ROCM_INDEX="$2"; shift 2 ;;
    --arch) ROCM_ARCH="$2"; shift 2 ;;
    --constraints) CONSTRAINTS="$2"; shift 2 ;;
    --rocm) ROCM_PREFIX="$2"; shift 2 ;;
    --no-gfx-override) NO_GFX_OVERRIDE=1; GFX_OVERRIDE=""; shift ;;
    --skip-libero) SKIP_LIBERO=1; shift ;;
    --clean) CLEAN=1; shift ;;
    --skip-smoke) SKIP_SMOKE=1; shift ;;
    --status) STATUS_ONLY=1; shift ;;
    -y|--yes) ASSUME_YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

VENV_DIR="${VENV_DIR/#\~/$HOME}"
LIBERO_SRC="${LIBERO_SRC/#\~/$HOME}"

if [[ "${STATUS_ONLY}" == "1" ]]; then
  status
  exit 0
fi

command -v uv >/dev/null 2>&1 || die "uv not found — install: https://docs.astral.sh/uv/"
command -v "${PYTHON_BIN}" >/dev/null 2>&1 || die "${PYTHON_BIN} not found"

if [[ "${CLEAN}" == "1" && -d "${VENV_DIR}" ]]; then
  if [[ "${ASSUME_YES}" != "1" && -t 0 ]]; then
    read -r -p "Remove ${VENV_DIR}? [y/N] " ans
    [[ "${ans}" =~ ^[yY] ]] || die "aborted"
  fi
  log "Removing ${VENV_DIR}"
  rm -rf "${VENV_DIR}"
fi

log "Creating venv at ${VENV_DIR}"
if [[ -x "${VENV_DIR}/bin/python" && "${CLEAN}" != "1" ]]; then
  log "Reusing existing venv (use --clean to recreate)"
else
  uv venv "${VENV_DIR}" --python "${PYTHON_BIN}" --allow-existing
fi

PY="${VENV_DIR}/bin/python"
INDEX_URL="${ROCM_INDEX%/}/"
log "Installing ROCm PyTorch from ${INDEX_URL} (arch ${ROCM_ARCH})"
if [[ -f "${CONSTRAINTS}" && -s "${CONSTRAINTS}" ]]; then
  uv pip install --python "${PY}" \
    -r "${CONSTRAINTS}" \
    --index-url "${INDEX_URL}" \
    --extra-index-url https://pypi.org/simple \
    --prerelease allow \
    --index-strategy unsafe-best-match \
    --refresh
else
  uv pip install --python "${PY}" \
    "torch[device-${ROCM_ARCH}]" "torchvision[device-${ROCM_ARCH}]" torchaudio "rocm[devel]" \
    --index-url "${INDEX_URL}" \
    --extra-index-url https://pypi.org/simple \
    --prerelease allow \
    --index-strategy unsafe-best-match \
    --refresh
fi

before_torch="$("${PY}" -c "import torch; print(torch.__version__)")"
log "torch (keep ROCm): ${before_torch}"

log "Installing ninja + safetensors (W4A4 HIP extension + pack)"
uv pip install --python "${PY}" ninja safetensors --extra-index-url https://pypi.org/simple

log "Installing lerobot[pi,dataset] @ ${LEROBOT_REF} --no-deps"
uv pip install --python "${PY}" --no-deps \
  "lerobot[pi,dataset]@git+https://github.com/huggingface/lerobot.git@${LEROBOT_REF}"
uv pip install --python "${PY}" \
  -r "${PKG_ROOT}/requirements-lerobot-runtime.txt" \
  --extra-index-url https://pypi.org/simple

log "Installing transformers 5.4.x (LeRobot PI05)"
uv pip uninstall --python "${PY}" transformers || true
uv pip install --python "${PY}" "transformers>=5.4.0,<5.6.0" --extra-index-url https://pypi.org/simple

if [[ "${SKIP_LIBERO}" != "1" ]]; then
  log "Fetching LIBERO source if needed"
  bash "${PKG_ROOT}/scripts/download_checkpoints.sh" libero
  if [[ -z "${LIBERO_SRC}" ]]; then
    if [[ -n "${LIBERO_ROOT:-}" && -d "${LIBERO_ROOT}/libero" ]]; then
      LIBERO_SRC="${LIBERO_ROOT}"
    elif [[ -d "${HOME}/openpi/third_party/libero/libero" ]]; then
      LIBERO_SRC="${HOME}/openpi/third_party/libero"
    elif [[ -d "${HOME}/model_data/libero/libero" ]]; then
      LIBERO_SRC="${HOME}/model_data/libero"
    elif [[ -d "${PKG_ROOT}/.vendor/libero/libero" ]]; then
      LIBERO_SRC="${PKG_ROOT}/.vendor/libero"
    else
      LIBERO_SRC="${HOME}/model_data/libero"
    fi
  fi
  log "Installing LIBERO sim runtime (robosuite + mujoco)"
  uv pip install --python "${PY}" \
    -r "${PKG_ROOT}/requirements-libero-sim.txt" \
    --extra-index-url https://pypi.org/simple
  [[ -d "${LIBERO_SRC}/libero" ]] || die "LIBERO source missing at ${LIBERO_SRC} after clone"
  log "Installing LIBERO editable from ${LIBERO_SRC}"
  uv pip install --python "${PY}" -e "${LIBERO_SRC}"
  touch "${LIBERO_SRC}/libero/__init__.py" 2>/dev/null || true
fi

after_torch="$("${PY}" -c "import torch; print(torch.__version__)")"
if [[ "${after_torch}" != "${before_torch}" ]]; then
  die "torch changed ${before_torch} -> ${after_torch}; abort"
fi

log "Making optional lerobot policies config-only (avoid unused import cycles)"
"${PY}" <<'PY'
from pathlib import Path
import lerobot
policies = Path(lerobot.__file__).parent / "policies"
for name in (
    "groot", "eo1", "wall_x", "xvla", "molmoact2", "vla_jepa", "pi0", "pi0_fast",
    "smolvla", "act", "diffusion", "tdmpc", "vqbet", "gaussian_actor", "multi_task_dit",
):
    pkg = policies / name
    init = pkg / "__init__.py"
    if not init.is_file():
        continue
    cfgs = sorted(pkg.glob("configuration_*.py"))
    if not cfgs:
        continue
    lines = ["# config-only stub written by pi05-pytorch-fast setup.sh\n"]
    for cfg in cfgs:
        lines.append(f"from .{cfg.stem} import *  # noqa: F403\n")
    init.write_text("".join(lines))
    print("config-only", init)
PY

write_env_snippet

if [[ "${SKIP_SMOKE}" != "1" ]]; then
  log "GPU smoke test"
  gpu_smoke_test
  log "LeRobot PI05 import smoke"
  "${PY}" -c "from lerobot.policies.pi05 import PI05Policy; print('OK', PI05Policy)"
fi

echo ""
log "Done"
echo "  source ${ENV_SNIPPET}"
echo "  python ${PKG_ROOT}/scripts/pack_w4a4_prefix.py"
echo "  python ${PKG_ROOT}/scripts/libero_eval.py --tasks libero_10 --episodes 2 --seed 0"
status
